language: python
python:
- "2.7"
# install dependencies
install: "pip install -r requirements.txt"
# run tests
script: coverage run --include="blogengine/*" --omit="blogengine/migrations/*" manage.py test blogengine
after_success:
    coveralls